export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
  GUEST = "GUEST",
}

export enum EstateCategory {
  SALE = "SALE",
  RENT = "RENT",
  SERVICE = "SERVICE",
}

export enum EstateStatus {
  PUBLISHED = "PUBLISHED",
  DRAFT = "DRAFT",
  ARCHIVED = "ARCHIVED",
  TRASHED = "TRASHED",
  SOLD = "SOLD",
  RENTED = "RENTED",
}

export enum EstateType {
  APARTMENT = "APARTMENT",
  HOUSE = "HOUSE",
  OFFICE = "OFFICE",
  GARAGE = "GARAGE",
  LAND = "LAND",
  COMMERCIAL = "COMMERCIAL",
  ROOM = "ROOM",
  VILLA = "VILLA",
  COTTAGE = "COTTAGE",
  OTHER = "OTHER",
}

export enum EstateCondition {
  NEW = "NEW",
  USED = "USED",
  REFINISHED = "REFINISHED",
}

export enum EstateAmenity {
  AIR_CONDITIONING = "AIR_CONDITIONING",
  CENTRAL_HEATING = "CENTRAL_HEATING",
  INTERNET = "INTERNET",
  WASHING_MACHINE = "WASHING_MACHINE",
  DISHWASHER = "DISHWASHER",
  TV = "TV",
  KITCHEN = "KITCHEN",
  GARAGE = "GARAGE",
  PARKING = "PARKING",
  GYM = "GYM",
  SWIMMING_POOL = "SWIMMING_POOL",
  GARDEN = "GARDEN",
  POOL = "POOL",
  GUEST_TOILET = "GUEST_TOILET",
  SECURITY = "SECURITY",
  SECURITY_CAMERA = "SECURITY_CAMERA",
  FIRE_EXTINGUISHER = "FIRE_EXTINGUISHER",
  SECURITY_GUARD = "SECURITY_GUARD",
  SECURITY_DOOR = "SECURITY_DOOR",
  SECURITY_ALARMS = "SECURITY_ALARMS",
}

export enum EstateRentPeriod {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}
